# Generated by Django 2.0.2 on 2018-02-06 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
